### ISSUE TITLE
Write Filter Exceptions for TPM Module

### ISSUE THREAD

**Issue by bderuijsscher** [ms-iot/iot-core-azure-dm-client#271]
Hello,

we are experiencing issues that causes unstable (non persistent) connections to Azure IoT hub when using the embedded Write Filter in IoT Core. 

This is that case: whenever we setup a device (retail image mode) it has its Write Filter disabled. We setup the device with all required functionalities, including a working connection to Azure IoT Hub. After all checks turn out to be OK (amongst others remote management via Azure IoT Hub), we enable the Write Filter to "seal" the device to allow it to be more resilient to sudden power losses (it is a headless device).

This is the initialization used to configure the Write Filter (in a .bat file):

```
REM Enables the write filter 
uwfmgr.exe filter enable 

REM Protects the Volume C
uwfmgr.exe volume protect c:  

REM Protected the Volume u (Data)
uwfmgr.exe file Add-Exclusion C:\Data\Users\System\AppData\Local\UpdateStagingRoot
uwfmgr.exe file Add-Exclusion C:\Data\SharedData\DuShared
uwfmgr.exe file Add-Exclusion C:\Data\SystemData\temp
uwfmgr.exe file Add-Exclusion C:\Data\users\defaultaccount\appdata\local\temp
uwfmgr.exe file Add-Exclusion C:\Data\Programdata\softwaredistribution
uwfmgr.exe file Add-Exclusion C:\Data\systemdata\nonetwlogs
uwfmgr.exe file Add-Exclusion C:\Data\Users\DefaultAccount\AppData\Local\Packages\[OUR APPLICATION DIR]
uwfmgr.exe volume protect u:
```

It seems to allow proper updates of Windows IoT core itself so does suggest a proper functioning Write filter / update system. 

The question remains why the Azure IoT Hub connection fails to have a persistent connection. Does the IoTDMClientLib store some kind of references in the Registry and/or Filesystem?

Many thanks for any assistance, regards

**Comment by gmileka** [comment]
bderuijsscher,
SystemConfigurator does some writes to the registry and the disk. IoTDMClientLib also writes to disk sometimes - depending on the scenarios.

Are you able to repro an instance of the problem consistently? I'm interested in where the failure is exactly... (Azure SDK, IoTDMClientLib, SystemConfigurator, etc).

**Comment by bderuijsscher** [comment]
Hi @gmileka ,
thanks for your response. I have further investigated and found the following error log. Not sure if this relates to TPM (probably not, as I have diagnosed the same issue when not using the Write Filter at all consistently). Could you provide any hint where to diagnose/fix this issue:

```
[InitializeDeviceClientAsync] InitializeDeviceClientAsync exception: CONNECT failed: RefusedNotAuthorized
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Void System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task) + 0x52
   at Void System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task) + 0x34
   at Void System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task) + 0x1c
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable<System.Int32>.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttTransportHandler.<OpenAsync>d__62.MoveNext()
   at Microsoft.Azure.Devices.Client.Transport.TransportHandler.<>c__DisplayClass3_0.<HandleTimeoutCancellation>b__1(Threading.Tasks.Task t)
   at Void System.Action`1.Invoke(T) + 0x18
   at Void System.Threading.Tasks.ContinuationTaskFromTask.InnerInvoke() + 0x3e
   at Void System.Threading.Tasks.Task.Execute() + 0x1c
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Void System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task) + 0x52
   at Void System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task) + 0x34
   at Void System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task) + 0x1c
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttTransportHandler.<OpenAsync>d__45.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Void System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task) + 0x52
   at Void System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task) + 0x34
   at Void System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task) + 0x1c
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.Azure.Devices.Client.Transport.ProtocolRoutingDelegatingHandler.<TryOpenPrioritizedTransportsAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Azure.Devices.Client.Transport.ProtocolRoutingDelegatingHandler.<TryOpenPrioritizedTransportsAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Void System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task) + 0x52
   at Void System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task) + 0x34
   at Void System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task) + 0x1c
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.Azure.Devices.Client.Transport.ProtocolRoutingDelegatingHandler.<OpenAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Void System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task) + 0x52
   at Void System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task) + 0x34
   at Void System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task) + 0x1c
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.<>c__DisplayClass19_0.<<ExecuteWithErrorHandlingAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Void System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task) + 0x52
   at Void System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task) + 0x34
   at Void System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task) + 0x1c
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable<System.Int32>.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.<ExecuteWithErrorHandlingAsync>d__20<System.Int32>.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.<ExecuteWithErrorHandlingAsync>d__20<System.Int32>.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Void System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task) + 0x52
   at Void System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task) + 0x34
   at Void System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task) + 0x1c
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.<OpenAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Void System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task) + 0x52
   at Void System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task) + 0x34
   at Void System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task) + 0x1c
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.<OpenAsync>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Void System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task) + 0x52
   at Void System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task) + 0x34
   at Void System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task) + 0x1c
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.Azure.Devices.Client.Transport.GateKeeperDelegatingHandler.<EnableTwinPatchAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Void System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task) + 0x52
   at Void System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task) + 0x34
   at Void System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task) + 0x1c
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.Azure.Devices.Client.DeviceClient.<>c__DisplayClass89_0.<<SetDesiredPropertyUpdateCallbackAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Void System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task) + 0x52
   at Void System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task) + 0x34
   at Void System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task) + 0x1c
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.Azure.Devices.Client.TaskHelpers.<WithTimeout>d__15.MoveNext()
   at Microsoft.Azure.Devices.Client.DeviceClient.<>c.<ApplyTimeout>b__74_2(Threading.Tasks.Task t)
   at Void System.Action`1.Invoke(T) + 0x18
   at Void System.Threading.Tasks.ContinuationTaskFromTask.InnerInvoke() + 0x3e
   at Void System.Threading.Tasks.Task.Execute() + 0x1c
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Void System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task) + 0x52
   at Void System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task) + 0x34
   at Void System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task) + 0x1c
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at [APPNAME].MainPage.<ResetConnectionAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Void System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task) + 0x52
   at Void System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task) + 0x34
   at Void System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task) + 0x1c
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at [APPNAME].MainPage.<InitializeDeviceClientAsync>d__15.MoveNext()

```

Regards,

**Comment by bderuijsscher** [comment]
A little more information: it seems to function properly initially but after some period of time these errors start to appear and the connection with IoT Hub is lost.

**Comment by gmileka** [comment]
Hi bderuijsscher,

If it works initially, then it starts failing, I'd think it's not a problem related to TPM. I'm confused though...
The exception trace above shows InitializeDeviceClientAsync(). This function is only called once at startup in the Toaster sample. Are you calling it multiple times in your code? Or do you mean multiple times of spawning your applications? Either way, the SAS token returned by `tpmDevice.GetConnectionStringAsync();` should be valid for one hour.

Also, one way to isolate the source of the problem (i.e. whether it's from the DM library or from the Azure SDK) is to [enable ETL](https://github.com/ms-iot/iot-core-azure-dm-client/blob/master/docs/debugging.md).

**Comment by bderuijsscher** [comment]
Hi @gmileka ,

thanks for your response and assistance. The InitializeDeviceClientAsync() function is probably repeatedly called because there could not be established a proper connection with Azure IoT Hub (after for example being offline for several hours - power off). 

As I come to think of it, we do not have a proper way of provisioning the TPM module (external LetsTrust module) when the device is imaged in retail mode. We therefore provision the TPM module on the same device but then running a developer image and use the Iot Core Dashboard application to connect the device to Azure. When that succeeds, we restart the device with a proper retail image and -since the TPM contains the SAS token- the device will reconnect to Azure properly again.

However, it seems that refreshing this token fails when the connection is not actively maintained (for example in power off). Does this mean that provisioning also entails some files/registry entries that should be copied over?

Regards

**Comment by gmileka** [comment]
Hi bderuijsscher,

I'm closing this one here since we are talking off-line.
